name: Publish Release

on: workflow_dispatch

jobs:
  build:
    name: Build Branch
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Lint Code Base
        uses: psf/black@stable
        with:
          args: ". --check"
      - name: Run Tests
        run: |
          python3 -m pip install --upgrade coverage
          coverage run --source=./src/ setup.py test
      - name: Build Package
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
      - name: Upload to PyPi
        run: |
          python3 -m pip install --upgrade twine
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
